name: Test
on: [push]
jobs:
  test:
    name: Test Project
    runs-on: ubuntu-latest
    container:
      image: node:lts
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: test
        run: yarn test
